package:
    name: pyvoiceid_utils
    # String with the full SHA1 of the current HEAD
    version: {{ GIT_FULL_HASH }}

source:    
  path: ..

requirements:
  build:
    - python ==3.5
    - setuptools

  run:
    - python ==3.5
    - numpy

test:
  requires:
    - python ==3.5
    - numpy
    - scipy
    - h5py  
    - pytest

  imports:
    - pyvoiceid_utils 

  source_files:
    - tests

  commands:
    - python -m pytest

about:
  license: Proprietary
  summary: "PyVoiceID utilities Module"
  license_family: Proprietary
